version : "3.9"
services :
  discovery :
    build : platform-services/discovery/target/docker
    ports :
      - "8761:8761"
  apidateway :
    build : platform-services/apigateway/target/docker
    ports :
      - "8765:8765"
    links :
      - discovery
  one :
    build : business-services/one/target/docker
    links :
      - discovery
  two :
    build : business-services/two/target/docker
    links :
      - discovery
